"""
teste
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print("teste primeiro teste no fork")

@aql.dataframe(task_id="python_2")
def python_2_func():
    print("Teste segundo teste no fork")

default_args={
    "owner": "Claudio Correia,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-01", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Claudio Correia": "mailto:claudiorcorreias@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm6ik17yd02j301l01w52s1xu/cloud-ide/cm6m7quz50scy01mdcf2fh09r/cm6m81aqy0rkl01l0zizwo418",
    },
)
def teste():
    python_1 = python_1_func()

    python_2 = python_2_func()

dag_obj = teste()
